lang:
  desc: "&7｜&6系統&7｜&f飯娘：&7查看自己或者其他玩家的商店。"
  prefix: "&7｜&6系統&7｜&f飯娘：&7容器商店查詢結果 - 共 &f{total} &7筆資料。"
  coord: "&7｜&6系統&7｜&f飯娘：&7{num}. &e{name}"
  nothing: "&7｜&6系統&7｜&f飯娘：&7沒有任何商店。"
  hover:
    - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    - "&e商品：&7{name}"
    - "&e位置：&7{world} - {x} {y} {z}"
    - "&e類別：&7{type}"
    - "&e價格：&7{price} &a乙太&f（ꆙ）"
    - "&8▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
  selling: "&b出售"
  buying: "&d收購"

